config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get 'home'    => 'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'help'    => 'static_pages#help'

  resources :articles
  resources :pages

end

app/models/article.rb
class Article < ActiveRecord::Base

  has_many :associated_articles, class_name: 'PageArticle', foreign_key: 'article_id', dependent: :destroy
  has_many :pages, through: :associated_articles

  default_scope -> { order(:title) }

  mount_uploader :picture_file, PictureUploader
  mount_uploader :movie_file, MovieUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :main_article_header, presence: true, length: { maximum: 255 }
  validates :main_article_body, presence: true
  validates :main_article_footer, length: { maximum: 255 }
  validates :side_article_header, length: { maximum: 255 }
  validates :side_article_footer, length: { maximum: 255 }
  validates :picture_alt_text, length: { maximum: 255 }
  validates :picture_caption, length: { maximum: 255 }
  validates :movie_alt_text, length: { maximum: 255 }
  validates :movie_caption, length: { maximum: 255 }

  validate :picture_size   # See custom validator below
  validate :movie_size   # See custom validator below


  def get_main_article_body_as_tokens
    main_article_body.split(/(!picture)|(!movie)|(!break)/)
  end


  def get_side_article_body_as_tokens
    side_article_body.split(/(!picture)|(!movie)|(!break)/)
  end


  private


  # Validates the size of an uploaded picture.
  def picture_size
    if picture_file.size > 3.megabytes
      errors.add(:picture_file, 'should be less than 3MB')
    end
  end


  # Validates the size of an uploaded movie.
  def movie_size
    if movie_file.size > 10.megabytes
      errors.add(:movie_file, 'should be less than 10MB')
    end
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  def index   # i.e. /articles with GET
    @articles = Article.paginate(page: params[:page], per_page: 10)
  end


  def show   # i.e. /articles/1 with GET
    @article = Article.find(params[:id])
  end


  def edit   # i.e. /articles/1/edit with GET
    @article = Article.find(params[:id])
  end


  def create   # /articles with POST
    @article = Article.new(permitted_params)

    if @article.save
      flash[:info] = 'New article has been saved.'
      # redirect_to articles_url
      render 'edit'
    else
      render 'new'   # try again
      # render 'edit'
      # redirect_to edit_article_path(@article)
    end
  end


  def update   # /articles/1 with PATCH
    @article = Article.find(params[:id])

    if @article.update_attributes(permitted_params)
      flash[:success] = 'Article saved'
    end

    render 'edit'
  end


  def destroy   # /articles/1 with DELETE
    Article.find(params[:id]).destroy
    flash[:success] = 'Article deleted'
    redirect_to articles_url
  end


  def new   # /articles/new with GET
    @article = Article.new
  end


  private

  def permitted_params
    # not sure why content assist doesn't work here; perhaps cuz this is so general as not to know about the
    # Article object
    params.require(:article).permit(:title, :main_article_header, :main_article_body, :main_article_footer,
                                 :side_article_header, :side_article_body, :side_article_footer,
                                 :picture_file, :picture_alt_text, :picture_caption,
                                 :movie_file, :movie_alt_text, :movie_caption)
  end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<li>
  <%= link_to 'Edit', edit_article_path(article) %>
  <%= link_to 'Show', article %>
  <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %>

  <%-# seems like the following should have content assist, but does not -%>
  <div class="index_item_title">
    <%= article.title %>
  </div>

</li>

app/views/articles/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for(@article) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%- # seems like we should be able to get content assist here (but don't) -%>
        <%= f.label :title, '* Title' %>
        <%= f.text_field :title, class: 'form-control', autofocus: 'autofocus' %>


        <%= f.label :picture_file, 'Picture file (optional)' %>

        <%- # the complex if/else logic here is for showing the picture client side before saving -%>
        <% if @article.picture_file? %>
            <div id="picture_container">
              <div id="existing_pic_name">
                Existing picture: <%= @article.picture_file %>
              </div>
              <%= image_tag @article.picture_file.url, id: 'picture_preview' %>
            </div>
        <% else %>
            <div id="picture_container" class="zero_height">
              <div id="existing_pic_name">
                Existing picture: <%= @article.picture_file %>
              </div>
              <%= image_tag '', id: 'picture_preview', class: 'zero_height' %>
            </div>
        <% end %>

        <%= f.file_field :picture_file, class: 'input_file', accept: 'image/jpeg,image/gif,image/png' %>


        <%= f.label :picture_alt_text %>
        <%= f.text_field :picture_alt_text, class: 'form-control' %>

        <%= f.label :picture_caption %>
        <%= f.text_field :picture_caption, class: 'form-control' %>


        <%= f.label :movie_file, 'Movie file (optional, mp4 only)' %>

        <%- # the complex if/else logic here is for showing the movie client side before saving -%>
        <% if @article.movie_file? %>
            <div id="movie_container">
              <div id="existing_movie_name">
                Existing movie: <%= @article.movie_file %>
              </div>
              <%= video_tag @article.movie_file.url, id: 'movie_preview', controls: 'controls' %>
            </div>
        <% else %>
            <div id="movie_container" class="zero_height">
              <div id="existing_movie_name">
              </div>
              <%= video_tag @article.movie_file.url, id: 'movie_preview', class: 'zero_height', controls: 'controls' %>
            </div>
        <% end %>

        <%= f.file_field :movie_file, class: 'input_file', accept: 'video/mp4' %>


        <%= f.label :movie_alt_text %>
        <%= f.text_field :movie_alt_text, class: 'form-control' %>

        <%= f.label :movie_caption %>
        <%= f.text_field :movie_caption, class: 'form-control' %>



        <%= f.label :main_article_header, '* Main article header' %>
        <%= f.text_field :main_article_header, class: 'form-control' %>

        <%= f.label :main_article_body, '* Main article body' %>
        <div>
          Available keywords: <strong>!picture</strong> or <strong>!movie</strong> = insert picture/movie;
          <strong>!break</strong> = two line feeds
        </div>
        <%= f.text_area :main_article_body, class: 'form-control', rows: 5 %>

        <%= f.label :main_article_footer %>
        <%= f.text_field :main_article_footer, class: 'form-control' %>

        <%= f.label :side_article_header %>
        <%= f.text_field :side_article_header, class: 'form-control' %>

        <%= f.label :side_article_body %>
        <div>
          Available keywords: <strong>!picture</strong> or <strong>!movie</strong> = insert picture/movie;
          <strong>!break</strong> = two line feeds
        </div>
        <%= f.text_area :side_article_body, class: 'form-control', rows: 5 %>

        <%= f.label :side_article_footer %>
        <%= f.text_field :side_article_footer, class: 'form-control' %>


        <%= f.submit 'Save', class: 'btn btn-primary' %>

        <%- # Apparently, it's a little tricky using a "button_to" -%>
        <%= link_to 'Cancel', :back, class: 'link_button btn btn-default wide_cancel' %>

    <% end %>

  </div>
</div>

<%- # TODO: consider coverting following Javascript to CoffeeScript and placing in asset pipeline -%>

<script type="text/javascript">

  createUploadFileOnChangeHandler('#article_picture_file', 'picture', 3, '#existing_pic_name', '#picture_preview');

  createUploadFileOnChangeHandler('#article_movie_file', 'movie', 10, '#existing_movie_name', '#movie_preview');

</script>

app/views/articles/edit.html.erb
<% provide(:title, @article.title) %>
<h2>Edit Article - <%= @article.title %> <small><%= link_to '[show]', article_path(@article) %></small></h2>

<%= render 'form' %>

app/views/articles/index.html.erb
<% provide(:title, 'All Articles') %>

<h1>All Articles</h1>

<div>
<%= link_to 'Create New Article', new_article_path %>
</div>

<%= will_paginate %>

<ul class="index_list">
  <%= render @articles %>
</ul>

app/views/articles/new.html.erb
<% provide(:title, 'Create New Article') %>
<h2>Create New Article</h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>
<div class="row">

  <h2>Article Details - <%= @article.title %> <small><%= link_to '[edit]', edit_article_path(@article) %></small></h2>

  <%= render 'shared/one_article',
             p_article: @article,
             p_main_article_elem_class: 'col-md-8',
             p_side_article_elem_class: 'col-md-4'  %>

</div>