config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get 'home'    => 'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'help'    => 'static_pages#help'

  resources :articles
  resources :pages

end

app/views/pages/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for(@page) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%- # seems like we should be able to get content assist here (but don't) -%>
        <%= f.label :title, '* Title' %>
        <%= f.text_field :title, class: 'form-control', autofocus: 'autofocus' %>

        <div class="panels_depiction">
          <div class="panels_caption">
            Page layout
          </div>
          <div class="depiction_row row">
            <div class="depiction_col col-md-3 depiction_top depiction_left">
              Panel 1
            </div>
            <div class="depiction_col col-md-3 depiction_top depiction_right">
              Panel 2
            </div>
          </div>
          <div class="depiction_row row">
            <div class="depiction_col col-md-3 depiction_bottom depiction_left">
              Panel 3
            </div>
            <div class="depiction_col col-md-3 depiction_bottom depiction_right">
              Panel 4
            </div>
          </div>
        </div>

        <% 4.times do |n| %>
            <%= render 'form_panel_options', panel_number: n + 1 %>
        <% end %>

<%- # The following block was temporarily inline until I moved it to a partial as shown above -%>
<% if false %>
        <%= f.label "article_id_panel_1", 'Panel 1 article' %>
        <%= select('article_id', 'panel_1', @all_articles.collect {|a| [ a.title, a.id ] },
                   { include_blank: true, selected: @pa_article_id[:panel_1] },
                   { class: 'form-control' } ) %>

        <%= f.label "style_number_panel_1", 'Panel 1 style' %>
        <%= select('style_number', 'panel_1', @all_styles.collect {|s| [ s[:title], s[:id] ] },
                   { include_blank: false, selected: @pa_style_number[:panel_1] },
                   { class: 'form-control' } ) %>
<% end %>

        <%= f.submit 'Save', class: 'btn btn-primary' %>

        <%- # Apparently, it's a little tricky using a "button_to" -%>
        <%= link_to 'Cancel', :back, class: 'link_button btn btn-default wide_cancel' %>

    <% end %>

  </div>
</div>

app/views/pages/_form_panel_options.html.erb
<div class="form_panel_options">

<label for="article_id_panel_<%= panel_number %>">Panel <%= panel_number %> article</label>

<%= select('article_id', "panel_#{panel_number}", @all_articles.collect {|a| [ a.title, a.id ] },
           { include_blank: true, selected: @pa_article_id["panel_#{panel_number}".to_sym] },
           { class: 'form-control' } ) %>

<label for="style_number_panel_<%= panel_number %>">Panel <%= panel_number %> style</label>

<%= select('style_number', "panel_#{panel_number}", @all_styles.collect {|s| [ s[:title], s[:id] ] },
           { include_blank: true, selected: @pa_style_number["panel_#{panel_number}".to_sym] },
           { class: 'form-control' } ) %>

</div>

app/views/pages/_page.html.erb
<li>
  <%= link_to 'Edit', edit_page_path(page) %>
  <%= link_to 'Show', page %>
  <%= link_to 'Delete', page, method: :delete, data: { confirm: 'Are you sure?' } %>

  <%-# seems like the following should have content assist, but does not -%>
  <div class="index_item_title">
    <%= page.title %>
  </div>

</li>

app/views/pages/edit.html.erb
<% provide(:title, @page.title) %>
<h2>Edit Page - <%= @page.title %> <small><%= link_to '[show]', page_path(@page) %></small></h2>

<%= render 'form' %>

app/views/pages/index.html.erb
<% provide(:title, 'All Pages') %>

<h1>All Pages</h1>

<div>
  <%= link_to 'Create New Page', new_page_path %>
</div>

<%= will_paginate %>

<ul class="index_list">
  <%= render @pages %>
</ul>

app/views/pages/new.html.erb
<% provide(:title, 'Create New Page') %>
<h2>Create New Page</h2>

<%= render 'form' %>

app/views/pages/show.html.erb
<% provide(:title, @page.title) %>

<div class="row">
  <h2>Page Details - <%= @page.title %> <small><%= link_to '[edit]', edit_page_path(@page) %></small></h2>
</div>

<div class="row first_panel_row">
  <%= render 'shared/one_panel', p_article: @panel_1_article, p_style_number: @panel_1_style, p_panel_number: 1 %>
  <%= render 'shared/one_panel', p_article: @panel_2_article, p_style_number: @panel_2_style, p_panel_number: 2 %>
</div>

<div class="row second_panel_row">
  <%= render 'shared/one_panel', p_article: @panel_3_article, p_style_number: @panel_3_style, p_panel_number: 3 %>
  <%= render 'shared/one_panel', p_article: @panel_4_article, p_style_number: @panel_4_style, p_panel_number: 4 %>
</div>


<%- # The rest of the page is only output in a development environment -%>

<% if Rails.env.development? %>
<div class="page_article_data row">

  <div>
    Attached articles:
  </div>

  <ul>
    <% @page.attached_articles.each do |attached_article| %>
        <li>
          Page id: <%= attached_article.page_id %>,
          Article id: <%= attached_article.article_id %>,
          Panel number: <%= attached_article.panel_number %>,
          Style number: <%= attached_article.style_number %>
        </li>
    <% end %>
  </ul>

  <div>
    Attached article content:
  </div>

  <ul>
    <% @page.articles.each do |article| %>
        <li>
          Id: <%= article.id %>,
          Title: <%= article.title %>,
          Main article hdr: <%= article.main_article_header %>
        </li>
    <% end %>
  </ul>

</div>
<% end %>