config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get 'home'    => 'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'help'    => 'static_pages#help'

  resources :articles
  resources :pages

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  developed by S Swett Dec 2014
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "page maker app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Help', help_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'Pages', pages_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">

  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>